### ISSUE TITLE
Why not leverage biocontainers?

### ISSUE THREAD

**Issue by brainstorm** [HumanCellAtlas/skylab#145]
... instead of (re-)writing those Dockerfiles under `docker`? 

See: http://biocontainers.pro/

/cc @biocontainers

**Comment by kbergin** [comment]
Hi @brainstorm Apologies I missed your issue when you filed it! We will look into Biocontainers, thanks for sharing!

**Comment by brainstorm** [comment]
Curious about what was the conclusions/outcomes on not using BioContainers? :)

**Comment by kbergin** [comment]
Hi @brainstorm! We haven't specifically decided not to use BioContainers, but haven't pushed our dockers there yet either.

We are moving towards using a GCR hosted source for our dockers for production because of the scale we run our pipelines. We also plan to push the same docker images to multiple locations so they are accessible to more people. Would it make sense to push a docker image to GCR, dockerhub, and biocontainers? Or am I misunderstanding what biocontainers is?

**Comment by brainstorm** [comment]
Yes it could make sense to push to several locations for redundancy and availability (I guess). 

The main advantage of biocontainers though is that you have already built (bio) scientific containers which you can "compose" without duplicating work. Also the community and practices around it are already established. Furthermore, the way to build such containers is already uniform and consistent, with documented guidelines and good practices.

Re-starting all that effort from scratch sounds redundant unless there are good reasons underneath?

**Comment by kbergin** [comment]
I'm likely just not understanding where we are proposing duplicating or restarting. I'll have an engineer on my team help me understand tomorrow. 

We use GCR for storing and calling out to our containers in production because of the scale we run at. We previously had issues with making too many docker pulls from Dockerhub, it was costing them a lot of money. On GCR we can cover the cost of hosting and pulling ourselves.

**Comment by brainstorm** [comment]
Sorry I did not mean the infrastructure or "Container Registry", GCR is perfectly fine. What I meant was the Dockerfile definitions/packaging/testing itself, i.e:

https://github.com/HumanCellAtlas/skylab/blob/master/docker/samtools/Dockerfile

vs 

https://github.com/BioContainers/containers/tree/master/samtools

Contributing those Dockerfiles to biocontainers instead of creating them yourself at skylab can potentially save a lot of individual efforts by leveraging community work and create a more uniform/robust/predictable ecosystem.

Hope it makes sense now ;)

**Comment by kbergin** [comment]
This is noted in our team backlog, closing issue as we are moving repositories.

**Comment by brainstorm** [comment]
Where?

**Comment by kbergin** [comment]
Our backlog is not public, unfortunately, but the new repo is here https://github.com/broadinstitute/warp
